"""Build the canonical root stylesheet from source CSS modules.

GitHub Pages and the existing HTML pages load /styles.css. Edit the files in
assets/css/ and run this script to regenerate that canonical stylesheet.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CSS_DIR = ROOT / "assets" / "css"
OUT = ROOT / "styles.css"

MODULES = [
    "tokens.css",
    "base.css",
    "layout.css",
    "navigation.css",
    "components.css",
    "pages-home.css",
    "pages-courses.css",
    "pages-tools.css",
    "pages-cv.css",
    "pages-mathclub.css",
    "pages-review.css",
    "utilities.css",
    "print.css",
]


def main() -> int:
    missing = [name for name in MODULES if not (CSS_DIR / name).is_file()]
    if missing:
        raise SystemExit(f"Missing CSS module(s): {', '.join(missing)}")

    parts = [
        "/* Generated by scripts/build_css.py. Edit assets/css/*.css instead. */",
        "@layer tokens, base, layout, navigation, components, pages, utilities, print;",
        "",
    ]

    for name in MODULES:
        path = CSS_DIR / name
        parts.append(f"/* === {name} === */")
        parts.append(path.read_text(encoding="utf-8").strip())
        parts.append("")

    OUT.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Built {OUT.relative_to(ROOT)} from {len(MODULES)} modules.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
